- name: Instalando pacotes genericos
  package:
    name:
      - php
    state: present    
    update_cache: yes

- name: Instala pacotes (Debian)
  package:
    name: 
      - apache2
      - mariadb-server
    state: present
    update_cache: yes
  when: ansible_os_family|lower == 'debian'

- name: Instala pacotes (EL)
  package:
    name: 
      - httpd
      - mariadb
    state: present
    update_cache: yes
  when: ansible_os_family|lower == 'redhat'
