- name: Minha primeira playbook
  hosts: 
    - docker
    - devops
  tasks: 
    - name: Instalando pacotes  
      package: 
        name: '{{ item }}'
        state: present       
      with_items:
        - cowsay
        - vim
        - htop           
    
    - name: Adicionando um usuario
      user:
        name: '{{ item }}'
        shell: '/bin/bash'
        password: '$1$ZNvbfY7m$8tJWRaFjZgM8HXG7eKLlY0'
      with_items:
        - devops  
        - developer
        - tiagosleal
    
    - name: Copiando arquivo de configuracao
      copy:
        src: devops
        dest: /tmp/devops.backup

- name: Minha primeira playbook no CentOS
  hosts: automation
  tasks:  
    - name: Instalando pacotes  
      package: 
        name: '{{ item }}'
        state: present       
      with_items:
        - cowsay
        - vim
        - htop   
        - epel-release        
